### ISSUE TITLE
IllegalStateException - duplicate key

### ISSUE THREAD

**Issue by normantshuva** [JetBrains/teamcity-vmware-plugin#15]
Hello, I tried using the teamcity vmware plugin on our VSphere, but unfortunately we could not make it work. In our vsphere we have lots of virtual machines with the same name, but when configuring an image (even if the image is from a unique vm) i get this exception:
IllegalStateException: duplicateKey
...
VmwareApiConnectorImpl.fetchInstances(VmwareApiConnectorImpl:458)
...

We can see at this line you assume uniqueness for vm names, which is not the case in our vsphere

**Comment by paksv** [comment]
Hi, it has been fixed in 2017.1.1, but if you are on older version, the best way is to just remove/rename duplicates

**Comment by normantshuva** [comment]
Hi,
Thanks for the response.
I am currently using version 2017.1.1 build 46654 and still have this issue.
Also, it seems that a dictionary with machine names as keys is used here:
 https://github.com/JetBrains/teamcity-vmware-plugin/blob/master/cloud-vmware-server/src/main/java/jetbrains/buildServer/clouds/vmware/connector/VMWareApiConnectorImpl.java#L458
Unfortunately, removing or renaming machines is not an option in my environment.

Thank you for the support.

**Comment by paksv** [comment]
Hi, this should have been refixed in 2017.1.2. Please let me know, if it still doesn't work for you.

Please note that non-unique VM cannot be used as a source VM for cloning or start-stop
